global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 15s
      api_version: v1
scrape_configs:
  - job_name: storage_api
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
#          - storage:5000
#          - storage:5001
          - host.docker.internal:5001

  - job_name: 'postgres'
    static_configs:
      - targets:
          - postgres_exporter:9187
    metrics_path: /metrics

  - job_name: pg_bouncer_exporter
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /
    scheme: http
    static_configs:
      - targets:
          - pg_bouncer_exporter:9127