name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Test / OS ${{ matrix.platform }} / Node ${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-18.04]
        node: ['12']

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Set up .env file
        run: |
          touch .env
          echo ANON_KEY=${{ secrets.ANON_KEY }} >> .env
          echo SERVICE_KEY=${{ secrets.SERVICE_KEY }} >> .env
          echo PROJECT_REF=${{ secrets.PROJECT_REF }} >> .env
          echo REGION=${{ secrets.REGION }} >> .env
          echo POSTGREST_URL=${{ secrets.POSTGREST_URL }} >> .env
          echo GLOBAL_S3_BUCKET=${{ secrets.GLOBAL_S3_BUCKET }} >> .env
          echo PGRST_JWT_SECRET=${{ secrets.PGRST_JWT_SECRET }} >> .env
          echo AUTHENTICATED_KEY=${{ secrets.AUTHENTICATED_KEY }} >> .env
          echo DATABASE_URL=postgresql://postgres:postgres@127.0.0.1/postgres >> .env
          echo PGOPTIONS='-c search_path=storage' >> .env
          echo FILE_SIZE_LIMIT=52428800 >> .env
          echo STORAGE_BACKEND=s3 >> .env

      - name: Install dependencies
        run: |
          npm ci

      - name: Prettier checks
        run: |
          npm run prettier:check

      - name: ESLint checks
        run: |
          npm run eslint:check

      - name: Builds successfully
        run: |
          npm run build

      - name: Tests pass
        run: |
          npm test
